### ISSUE TITLE
error with latest version of knex

### ISSUE THREAD

**Issue by jamesdixon** [jfgodoy/knex-postgis#16]
Hi, first off, great work on this project!

I just upgraded to Knex 0.12 and am now receiving the following error:

```
/app/node_modules/knex-postgis/lib/index.js:12
  formatterProto = knex.client.Formatter.prototype
```

**Comment by jfgodoy** [comment]
thanks @jamesdixon for the report.
I just published a new version to npm that adds support for knex@0.12

**Comment by jamesdixon** [comment]
Thanks for the quick fix!
