### ISSUE TITLE
Knex:warning - global Knex.raw is deprecated, use knex.raw (chain off an initialized knex object)

### ISSUE THREAD

**Issue by unimonkiez** [jfgodoy/knex-postgis#20]
While running I get his error

```bash
Knex:warning - global Knex.raw is deprecated, use knex.raw (chain off an initialized knex object)
```

Thanks in advance!

**Comment by jfgodoy** [comment]
thank you for the report, I will check it right now.

**Comment by jfgodoy** [comment]
It is not a `knex-postgis` issue. You need to pass a `Knex` instance to `knex-postgis`

**Wrong:**
This will print warnings
```
const knex = require('knex');
const st = require('knex-postgis')(knex);
const sql = knex.select('id', st.asText('geom')).from('points').toString();
console.log(sql);
```

**Right:**
```
// create a knex instance
const knex = require('knex')({
  dialect: 'postgres'
  // other params
});
const st = require('knex-postgis')(knex);
const sql = knex.select('id', st.asText('geom')).from('points').toString();
console.log(sql);
```

**Comment by unimonkiez** [comment]
Oh thanks man! works great.

Might got confused due to [this example](https://github.com/jfgodoy/knex-postgis/blob/master/README.md#example), the db creation is in the same line of the import, so I thought you should wrap knex object instead..

I opened a PR (#21) fixing the documentation.
