### ISSUE TITLE
Bounding box intersection question (&& operator)

### ISSUE THREAD

**Issue by RomanShumikhin** [jfgodoy/knex-postgis#23]
How do you represent a query like this in knex-postgis?
```
SELECT *
FROM mytable
WHERE mytable.geom && ST_MakeEnvelope(10.9351, 49.3866, 11.201, 49.5138, 4326);
```
http://postgis.net/docs/manual-2.0/geometry_overlaps.html
I couldn't find *&&* operator anywhere.
st.makeEnvelope(minlon, minlat, maxlon, maxlat, 4326) exists though....

Thanks!

**Comment by jfgodoy** [comment]
Hi, currently there is not implementation for `&&`. Let me see if I can implement it easely

**Comment by jfgodoy** [comment]
I just publish version 0.3.0 with support for `&&`.

**Comment by RomanShumikhin** [comment]
WOW! I didn't expect this to be resolved so fast :D Thank you very much @jfgodoy ! 👍 
There are two more handy operators there BTW: *@* and *~*
http://postgis.net/docs/manual-2.0/ST_Geometry_Contained.html
http://postgis.net/docs/manual-2.0/ST_Geometry_Contain.html

**Comment by jfgodoy** [comment]
:D
I just publish a new version. I renamed `boundingBoxIntersection` to `boundingBoxIntersects`
&& => boundingBoxIntersects(geom a, geom b)
@ => boundingBoxContained(geom a, geom b)
~ => boundingBoxContains(geom a, geom b)

**Comment by RomanShumikhin** [comment]
Awesome, thank you very much, @jfgodoy !
