### ISSUE TITLE
transform() function is failing due to pg library adding quotes around srid

### ISSUE THREAD

**Issue by aratcliffe** [jfgodoy/knex-postgis#26]
knex.raw() uses the pg library for SQL parameter binding. pg adds quotes around number literals causing some queries to fail, see https://github.com/tgriesser/knex/issues/1001. In knex-postgis this behaviour results in the SQL generated for the transform() function quoting the srid parameter. The resultant query fails with the error:

`ERROR:  transform_geom: couldn't parse proj4 output string: '4326': projection not named`

**Comment by jfgodoy** [comment]
thank @aratcliffe for this report. I reproduced the bug using knex <= 0.11, but it seems that starting from knex@0.12, the numbers are not quoted anymore.  Try to upgrade to a more recent version of knex and tell me if it works.

**Comment by jfgodoy** [comment]
I will close this issue due to lack of response.
