### ISSUE TITLE
Use bindings in knex.raw() calls instead of building inline strings

### ISSUE THREAD

**Issue by whitelynx** [jfgodoy/knex-postgis#3]
The current implementation is susceptible to SQL injection. As a trivial example, `knex.insert({id: 1, geom: st.geomFromText("Point(')); DROP TABLE points; SELECT concat(concat(')", 4326)}).into('points')` will generate the following query:
```sql
insert into "points" ("geom", "id") values (ST_geomFromText('Point(')); DROP TABLE points; SELECT concat(concat(')', 4326), '1')
```

Using bindings as described [in the knex docs](http://knexjs.org/#Raw-Expressions) avoids this, and will mostly negate the need for `formatter.wrapWKT()` and `formatter.wrapGeoJSON()`.

**Comment by jfgodoy** [comment]
oops! I will fix it in the next 24 hours.
thank you

**Comment by whitelynx** [comment]
For refererence, here's a simple version of what I've been using to wrap the PostGIS functions up until now:

```javascript
function functionCall(conn, name, args)
{
    var formatter = new conn.client.Formatter();

    var sql = name + '(' + formatter.parameterize(args) + ')';

    var funcCall = knex.raw(sql, formatter.bindings);
    var sqlWithoutAs = funcCall.sql;
    funcCall.as = function(alias)
    {
        this.sql = sqlWithoutAs + ' as ' + formatter.wrap(alias);
        return this;
    };

    return funcCall;
}

function defineFunction(conn, name)
{
    return function()
    {
        return functionCall(conn, name, Array.prototype.slice.call(arguments));
    };
}

// Usage examples: //
var pointWKT = 'POINT(-71.064544 42.28787)';
var query = localDB().select(functionCall(localDB, 'ST_GeomFromText', [pointWKT, 4326]));
query.toSQL() === { method: 'select',
  options: undefined,
  bindings: [ 'POINT(-71.064544 42.28787)', 4326 ],
  sql: 'select ST_GeomFromText(?, ?)' };

var geomFromText = defineFunction(localDB, 'ST_GeomFromText');
query = localDB().select(geomFromText(pointWKT, 4326));
query.toSQL() === { method: 'select',
  options: undefined,
  bindings: [ 'POINT(-71.064544 42.28787)', 4326 ],
  sql: 'select ST_GeomFromText(?, ?)' };

var geomFromGeoJSON = defineFunction(localDB, 'ST_GeomFromGeoJSON');
var pointGeoJSON = {type: 'Point', coordinates: [-71.064544, 42.28787]};
query = localDB().select(geomFromGeoJSON(pointGeoJSON, 4326));
query.toSQL() === { method: 'select',
  options: undefined,
  bindings: 
   [ { type: 'Point',
       coordinates: [ -71.064544, 42.28787 ] },
     4326 ],
  sql: 'select ST_GeomFromGeoJSON(?, ?)' };

query = localDB().select(geomFromGeoJSON(JSON.stringify(pointGeoJSON), 4326));
query.toSQL() === { method: 'select',
  options: undefined,
  bindings: 
   [ '{"type":"Point","coordinates":[-71.064544,42.28787]}',
     4326 ],
  sql: 'select ST_GeomFromGeoJSON(?, ?)' };
```

**Comment by jfgodoy** [comment]
I tried to use the bindings, but I need to support these cases:
```
var case1 = knex.select(st.x(st.geomFromText('Point(10 20)')));
var case2 = knex.select(st.x('geom'));
```
The bindings work well for the case1, but not for case2.

Any thoughts about this?

**Comment by jfgodoy** [comment]
I resolved the injection problem improving the wkt and geoJSON validation.
I will wait your opinions to close this issue and publish to npm

**Comment by whitelynx** [comment]
Well, that change will help with preventing SQL injection, but it doesn't really solve this issue - we really should be using bindings in our `knex.raw()` calls instead. This is important because it leverages the [parameterized query support in node-postgres](https://github.com/brianc/node-postgres/wiki/FAQ#8-does-node-postgres-handle-sql-injection), which not only protects against SQL injection, but allows PostgreSQL to cache and reuse query plans.

In order to work for the second case you gave above, just wrap the given column name in a `knex.raw()` call with no bindings:
```javascript
if (typeof value === 'string' && value.match(/^[^\{\}]*$/)) {
    return knex.raw(value);
}
```
(I omitted the `.toString()` call that's currently in `wrapGeoJSON()`, since we've already tested that `value` is a string)

----

As far as the rest of `wrapGeoJSON()`: You should not need to call `JSON.stringify()` at all, or wrap it in quotes; if you give `node-postgres` a plain object, it will automatically render it correctly as JSON.

**Comment by jfgodoy** [comment]
Thanks so much for your help. I will implement it after work.

**Comment by whitelynx** [comment]
No problem!

**Comment by jfgodoy** [comment]
`knex.raw(value)` do not escaped the value, so is susceptible to SQL Injection. Another alternative is to use `knex.raw(formatter.wrap(value))`, but I just discovered that knex's function wrap is also susceptible to SQL Injection, at least in postgreSQL dialect. 
for example if I do:
If I do:
```
var query = knex.select('id","name').from('test')
console.log(query.toSQL())
```
I get
```
{ method: 'select',
  options: undefined,
  bindings: [],
  sql: 'select "id","name" from "test"' }
```

The functions wrapWKT and wrapGeoJSON use the knex's wrap function, so the current implementation still is susceptible to SQL Injection :(

**Comment by tgriesser** [comment]
Pushing a fix now

**Comment by whitelynx** [comment]
@tgriesser It might be useful to have a `knex.identifier(name)` function to explicitly wrap something as an identifier, instead of having to get a formatter somehow and call `formatter.wrap(name)`.

**Comment by tgriesser** [comment]
Yeah it absolutely would be - I'm finally able to get back into the massive backlog of knex stuff next week and I will put this high on the priority list.

**Comment by jfgodoy** [comment]
now the implementation uses knex.raw bindings and works for both cases.

**Comment by whitelynx** [comment]
Looks good, thanks! :+1:

**Comment by whitelynx** [comment]
Could we get a new package release with these changes?

**Comment by jfgodoy** [comment]
ready! republished as 0.1.5
