### ISSUE TITLE
ST_transform add '' aroud SRID

### ISSUE THREAD

**Issue by GitMorin** [jfgodoy/knex-postgis#32]
Hi,

I just noticed that I got the same error for a closed issue regarding quotation around SRID.

`poi.geom = st.transform(st.geomFromText(poi.geom, 4326),25832);`
return
`insert into assets ("asset_type", "geom") values ('test', ST_transform(ST_geomFromText('POINT(11.356373786926271 64.45708785376902)', 4326), 25832))`
The returned SQL is fine and run correctly if I copy/paste it to run in pgadmin.
But I am getting an error 
`New poi error { error: transform_geom: couldn't parse proj4 output string: '25832': projection not named
`
If I add the quotation marks to the returned sql then I get the same error in postgis, so it looks like it is being parsed to a string at some point?

The version of knex I am using is 0.14.6

**Comment by jfgodoy** [comment]
Hi @GitMorin, your issue is related with #29. To solve that issue I made a PR #30 but I didn't receive any feedback so I closed it without merge it. I will reopen the PR so you can test it if it's work

**Comment by GitMorin** [comment]
Fantastic! Thanks it worked. Tested the code and could insert to the database as expected.

**Comment by jfgodoy** [comment]
I just published a new version, 0.8.0. See the changelog in the Readme, because I did other changes too.
thank you @GitMorin  for the feedback
