### ISSUE TITLE
ST_GeographyFromText ?

### ISSUE THREAD

**Issue by darkbasic** [jfgodoy/knex-postgis#38]
Is it missing?

**Comment by jfgodoy** [comment]
hi @darkbasic, the geographyFromText function is not currently available, but I can add it easily.  There are a lots of functions in postgis, so I only add a function on demand, but users can also add functions using https://github.com/jfgodoy/knex-postgis#define-extra-functions

I will add it and release a version.

**Comment by jfgodoy** [comment]
`geographyFromText`  is now available in version 0.11.0
