### ISSUE TITLE
ST_Z

### ISSUE THREAD

**Issue by SiBell** [jfgodoy/knex-postgis#40]
Just wondering if it would be possible to implement `ST_Z`? In order to extract the height coordinate.

Hopefully it's as simple as replicating much of what you've already done for `st.x` and `st.y` and creating a `st.z` function.

(P.s. thanks for a great package)

**Comment by jfgodoy** [comment]
hi @SiBell, thank you for your p.s !!
I can easily implement it after work.

**Comment by jfgodoy** [comment]
done! I added `z` and `m` functions.
published in v0.12.0

**Comment by SiBell** [comment]
Thanks @jfgodoy I've updated to 0.12.0 and `st.z` is working as expected 👍
