### ISSUE TITLE
SQL injection attack

### ISSUE THREAD

**Issue by Dakuan** [jfgodoy/knex-postgis#45]
the docs appear to be pushing us in this direction

```
const location = st.geomFromText(`POINT(${latitude} ${longitude})`, 4326)
```

but won't this lead to injection vulns? The signature for the method doesnt appear to have a paramerized version?

**Comment by jfgodoy** [comment]
Hi @Dakuan, thank your interest in this subject, 

The signature of `st.geomFromText` has the same parameters as the postgis function [st_geomFromText](https://postgis.net/docs/ST_GeomFromText.html). Internally, the function checks that the first argument seems to be a WKT string with the regex: 

`/^(srid=\d+;)?(geometry(collection)?|curvepolygon|((multi)?(point|polygon|curve|surface|linestring))|triangle|circularstring|CompoundCurve|PolyhedralSurface|TIN)\s*\([0-9,\s.()+-]*\)/i`. 

As you can see, there are a limited set of possible words. Also, quotes aren't allowed. If the first argument does not satisfy the regex, it is escaped using knex `??`, so it's interpreted as an identifier.

I think it's not possible to make an injection.

Hope this solves your questions.

**Comment by Dakuan** [comment]
heya @jfgodoy thanks for getting back to me. Yes I can see how this is solved right *now* however the safety of this function is contingent on all those things remaining true, rather than leveraging database primitivies. A bad future commit could introduce them. 

In general you should never ever ever use string concatenation for building SQL queries. For a large code bases with large teams if exceptions are made for this case then engineers could easily start making exceptions elsewhere.

I've swtiched to use `geomFromGeoJSON` instead to avoid string concatenation :)

```

  $formatDatabaseJson(json: Pojo): Pojo {
    json = super.$formatDatabaseJson(json);
    const { location } = json;

    return {
      ...json,
      location: st.geomFromGeoJSON(location as Point),
    };
  }```

**Comment by Dakuan** [comment]
re string concatention:

https://www.psycopg.org/docs/usage.html#passing-parameters-to-sql-queries

![image](https://user-images.githubusercontent.com/633621/109130979-3c6d1880-774a-11eb-8914-d76a9bc492b1.png)

**Comment by jfgodoy** [comment]
> ... A bad future commit could introduce them.

I did another check. Even if I break the regex and allow any string, when the query is passed to knex it's using knex params, so an injection isn't possible. 
```
// removing internal wkt check
knex.insert({
  id: 1,
  geom: st.geomFromText("Point'(0 0)", 4326)
}).into('points').toSQL();

// it's passed to knex as 
{
  sql: 'insert into "points" ("geom", "id") values (ST_geomFromText(?, ?), ?)',
  bindings: [ "Point'(0 0)", 4326, 1 ],
}
```

> 
> In general its a really bad idea to use string concatenation for building SQL queries. For a large code bases with large teams if exceptions are made for this case then engineers could easily start making exceptions elsewhere.

I really agree with you, and the solution you found is excellent. I want to keep the API equivalent to postgis, there are valid use cases where you already have a wkt and you can use it directly. Maybe another good solution, if someone needs to create a wkt, is to have a wkt builder. It would be more readable. For example, `wkt.Point(lat, long).setSrid(3857)`, but that'd be for another package.

**Comment by Dakuan** [comment]
ah good stuff @jfgodoy! Excellent work on this lib, it's great!
