### ISSUE TITLE
Replace @mapbox/geojsonhint

### ISSUE THREAD

**Issue by vulkd** [jfgodoy/knex-postgis#46]
`@mapbox/geojsonhint` was marked as deprecated, and contains dependencies with vulnerabilities identified via `npm audit`. See https://github.com/mapbox/geojsonhint/issues/83

Possible replacements:
 - https://github.com/placemark/check-geojson (from the original author of @mapbox/geojsonhint)
 - https://www.npmjs.com/package/geojson-validation

**Comment by jfgodoy** [comment]
hi @vulkd, I finally replaced `@mapbox/geojsonhint` with `check-geojson`. The changes are in master now, if you want to test them. 

I will publish a new version tomorrow.

**Comment by jfgodoy** [comment]
I've just published the new version.
