### ISSUE TITLE
Vulnerable Dependencies

### ISSUE THREAD

**Issue by bryan-vh** [jfgodoy/knex-postgis#48]
Since installing this package, I am receiving the following warning:

```
# npm audit report

underscore  1.3.2 - 1.12.0
Severity: high
Arbitrary Code Execution - https://npmjs.com/advisories/1674
fix available via `npm audit fix`
node_modules/underscore
  nomnom  >=1.6.0
  Depends on vulnerable versions of underscore
  node_modules/nomnom

2 high severity vulnerabilities

To address all issues, run:
  npm audit fix
```

But running "npm audit fix" doesn't actually fix the issues. Not sure how that will affect this library, but figured I'd let the maintainer (if there is still an active one) know.

**Comment by jfgodoy** [comment]
hi @bryan-vh, thank you for the report. The warning is due to a deprecated dependency used to check geojson values, as reported in #46.
I've just replaced the library  in master and I will publish a new version tomorrow.

**Comment by jfgodoy** [comment]
I've just published the new version that fixes this problem.
