### ISSUE TITLE
Unable to compile with TypeScript

### ISSUE THREAD

**Issue by aq1018** [jfgodoy/knex-postgis#49]
## Problem

I was unable to compile `knex-postgis` with TypeScript.

## How To Reproduce

I made a repository demonstrating the issue:

https://github.com/aq1018/knex-postgis-build-failure

## Fix

I think the `knex` exports signature has changed in recent versions, and is causing the definition file to be incompatible.

**Comment by jfgodoy** [comment]
hi @aq1018! thank you very much for this report and the fix.
I really appreciate that you have taken the time to make demo repo  :+1: 

I've just published a new version that includes the fix

**Comment by aq1018** [comment]
🎉
