### ISSUE TITLE
Creating a polygon

### ISSUE THREAD

**Issue by Alystrasz** [jfgodoy/knex-postgis#52]
Hello there,
I'm trying to create a polygon to insert into my database using `geomFromGeoJSON`, but I can't get it to work.

```javascript
const testGeom = App.St.geomFromGeoJSON({
    "type": "Polygon",
    "coordinates": [
        [
            [
                28.740234375,
                57.468589192089354
            ],
            [
                31.113281249999996,
                57.468589192089354
            ],
            [
                31.113281249999996,
                58.63121664342478
            ],
            [
                28.740234375,
                58.63121664342478
            ],
            [
                28.740234375,
                57.468589192089354
            ]
        ]
    ]
});
```

I get:
```text
(node:33452) UnhandledPromiseRejectionWarning: Error: Invalid GeoJSON
    at Object.checkGeoJsonGeometry (/home/remy/Travail/path-error-backend/node_modules/knex-postgis/lib/utils.js:30:15)
    at wrapGeoJSON (/home/remy/Travail/path-error-backend/node_modules/knex-postgis/lib/index.js:42:33)
    at Object.geomFromGeoJSON (/home/remy/Travail/path-error-backend/node_modules/knex-postgis/lib/functions.js:104:46)
```

According to https://geojsonlint.com, the GeoJSON is valid.

What am I doing wrong?
Thanks for your help.

**Comment by jfgodoy** [comment]
hi @Alystrasz, thank you for the report. Your are right, your geojson is valid. I've trace the issue and found that is related to a change in the library that I'm using for check geojson validity (see https://github.com/placemark/check-geojson/issues/20).

I have published a new version that fix the problem holding the latest version of @placemarkio/check-geojson that uses the old behaviour.

**Comment by Alystrasz** [comment]
New version seems to be working.
Thanks!
