### ISSUE TITLE
Knex.js 0.8.x support

### ISSUE THREAD

**Issue by vespakoen** [jfgodoy/knex-postgis#6]
With the newest knex.js, I get the following kind of errors:

```
insert into "kitchensinks" ("id", "type_boolean", "type_date", "type_datetime", "type_float", "type_integer", "type_json", "type_linestring", "type_point", "type_polygon", "type_string", "type_text", "type_uuid") values ($1, $2, $3, $4, $5, $6, $7, ST_geomFromGeoJSON($8), ST_geomFromGeoJSON($9), ST_geomFromGeoJSON($10), $11, $12, $13) - bind message supplies 10 parameters, but prepared statement "" requires 13
```

It seems the way raw types are handled introduce some incompatibility.

I wan't to investigate later but will stick with 0.7.x for now.

**Comment by jfgodoy** [comment]
I had fixed some issues to add support to knex 0.8.x in #7.
As you say, knex.raw break its api in 0.8.x, I added an issue https://github.com/tgriesser/knex/issues/853 in knex
Can you test if the changes added solve your problem?

**Comment by vespakoen** [comment]
Awesome, thanks mate! Will check this out later and report back...

**Comment by jfgodoy** [comment]
I will close this issue for now, if you still have problems with knex 0.8, let me know.
The new version is on npm as 0.1.8.
